// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFt_P7_yIom0f_IvNQYygUY4MmiWA42Dw',
    appId: '1:495352134114:web:6ad8d2b6afe68d69e461bb',
    messagingSenderId: '495352134114',
    projectId: 'assistance-for-the-elderly',
    authDomain: 'assistance-for-the-elderly.firebaseapp.com',
    storageBucket: 'assistance-for-the-elderly.appspot.com',
    measurementId: 'G-RYBTXWCP0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEu_BtnaYWCKVB2sOUuG8phA1FZ6HLRRQ',
    appId: '1:495352134114:android:f523c542d746d2b6e461bb',
    messagingSenderId: '495352134114',
    projectId: 'assistance-for-the-elderly',
    storageBucket: 'assistance-for-the-elderly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKfRfWeuwehlVnLnMhTKwmH7FkHCmvVlQ',
    appId: '1:495352134114:ios:cd320a98b608ab50e461bb',
    messagingSenderId: '495352134114',
    projectId: 'assistance-for-the-elderly',
    storageBucket: 'assistance-for-the-elderly.appspot.com',
    iosBundleId: 'com.example.tccassistencia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKfRfWeuwehlVnLnMhTKwmH7FkHCmvVlQ',
    appId: '1:495352134114:ios:cd320a98b608ab50e461bb',
    messagingSenderId: '495352134114',
    projectId: 'assistance-for-the-elderly',
    storageBucket: 'assistance-for-the-elderly.appspot.com',
    iosBundleId: 'com.example.tccassistencia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFt_P7_yIom0f_IvNQYygUY4MmiWA42Dw',
    appId: '1:495352134114:web:58390bc292009442e461bb',
    messagingSenderId: '495352134114',
    projectId: 'assistance-for-the-elderly',
    authDomain: 'assistance-for-the-elderly.firebaseapp.com',
    storageBucket: 'assistance-for-the-elderly.appspot.com',
    measurementId: 'G-8LDJ36VV3M',
  );
}
